### ISSUE TITLE
problem with 2.4.0, image didn;t show up

### ISSUE THREAD

**Issue by gettinlow** [fukata/wp-flickr-press#36]
everything seems normal but then when i add some photos, the photos didnt show up.
the link show was below:

<img class="aligncenter" alt="INTERSPORT - PONDOK CABE" />

<img class="aligncenter" alt="INTERSPORT - PONDOK CABE" />

<img class="aligncenter" alt="INTERSPORT - PONDOK CABE" />

no image source grab from the panel.

**Comment by fukata** [comment]
Please oauth again.
